controllers/CursosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cursan;
use app\models\Cursos;
use app\models\CursosSearch;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * CursosController implements the CRUD actions for Cursos model.
 */
class CursosController extends Controller {

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Muestra todos los modelos de `Cursos`.
     * Maneja la búsqueda y filtrado de cursos y la creación de nuevos cursos.
     * @return string Renderiza la vista 'index' con la lista de cursos.
     */
    public function actionIndex() {

        if(Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $searchModel = new CursosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = new Cursos();

        // Validación y creación del curso en caso de solicitud AJAX o POST
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model); // Devuelve la validación en formato JSON
        } elseif ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                Cursos::setSigla($model); // Asigna la sigla del curso
                Yii::$app->session->setFlash('success', 'El curso se ha añadido correctamente.');
                return $this->redirect(['index']);
            } else {
                Yii::$app->session->setFlash('error', 'Ha ocurrido un error al añadir el curso.');
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'model' => $model
        ]);

    }

    /**
     * Actualiza un modelo `Cursos` existente.
     * Redirige a la vista 'index' después de una actualización exitosa.
     * @param int $id_curso Id del curso a actualizar.
     * @return string|\yii\web\Response Renderiza la vista 'update' o redirige a 'index'.
     * @throws NotFoundHttpException si el modelo no se puede encontrar.
     */
    public function actionUpdate($id_curso) {

        $model = $this->findModel($id_curso);

        // Validación y actualización del curso en caso de solicitud AJAX o POST
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model); // Devuelve la validación en formato JSON
        } else {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                Cursos::setSigla($model); // Asigna la sigla del curso
                Yii::$app->session->setFlash('success', 'El curso se ha actualizado correctamente.');
                return (Yii::$app->request->isAjax) ? $this->renderAjax('update', ['model' => $model]) : $this->redirect(['index']);
            } else {
                return (Yii::$app->request->isAjax) ? $this->renderAjax('update', ['model' => $model]) : $this->render('update', ['model' => $model]);
            }
        }

    }

    /**
     * Elimina un modelo `Cursos` existente.
     * Redirige a la vista 'index' después de una eliminación exitosa.
     * @param int $id_curso Id del curso a eliminar.
     * @return \yii\web\Response Redirige a la vista 'index'.
     * @throws NotFoundHttpException si el modelo no se puede encontrar.
     */
    public function actionDelete($id_curso) {

        Cursan::deleteAll(['id_curso' => $id_curso]); // Elimina todas las relaciones del curso con alumnos

        $this->findModel($id_curso)->delete(); // Elimina el curso

        Yii::$app->session->setFlash('success', 'El curso se ha eliminado correctamente.');
        return $this->redirect(['index']);

    }

    /**
     * Encuentra el modelo `Cursos` basado en su clave primaria.
     * Lanza una excepción 404 si el modelo no se encuentra.
     * @param int $id_curso Id del curso.
     * @return Cursos El modelo cargado.
     * @throws NotFoundHttpException si el modelo no se puede encontrar.
     */
    protected function findModel($id_curso) {
        if (($model = Cursos::findOne(['id_curso' => $id_curso])) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('El curso no existe');
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Almacenes;
use app\models\Alumnos;
use app\models\Cargadores;
use app\models\Cargan;
use app\models\Cursan;
use app\models\Cursos;
use app\models\LoginForm;
use app\models\Portatiles;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Mostrar la página de inicio.
     *
     * @return string
     */
    public function actionIndex() {
        return $this->render('index');
    }

    /**
     * Mostrar la información de un portátil.
     *
     * @param string $codigo Código del portátil
     * @return string
     */
    public function actionPortatil($codigo) {

        $this->layout = '/main_nofooter';

        Cargan::sincronizarCargan();
        $portatil = Portatiles::find()->where(['codigo' => $codigo])->one();

        if ($portatil) {

            $portatil->sincronizarPortatil($portatil);

            $cargador = Cargadores::find()->select('cargadores.codigo')->distinct()->innerJoin(Cargan::tableName(), 'cargadores.id_cargador = cargan.id_cargador')->innerJoin(Portatiles::tableName(), 'cargan.id_portatil = portatiles.id_portatil')->where(['portatiles.codigo' => $codigo])->scalar();
            $almacen = Almacenes::find()->select('almacenes.aula')->distinct()->innerJoin(Portatiles::tableName(), 'almacenes.id_almacen = portatiles.id_almacen')->where(['portatiles.codigo' => $codigo])->scalar();
            $alumnoManana = Alumnos::find()->innerJoin(Cursan::tableName(), 'alumnos.id_alumno = cursan.id_alumno')->innerJoin(Cursos::tableName(), 'cursan.id_curso = cursos.id_curso')->innerJoin(Portatiles::tableName(), 'alumnos.id_portatil = portatiles.id_portatil')->where(['cursos.turno' => 'Mañana', 'estado_matricula' => "Matriculado", 'curso_academico' => Cursan::getCursoActual(), 'portatiles.codigo' => $codigo])->one();
            $alumnoTarde = Alumnos::find()->innerJoin(Cursan::tableName(), 'alumnos.id_alumno = cursan.id_alumno')->innerJoin(Cursos::tableName(), 'cursan.id_curso = cursos.id_curso')->innerJoin(Portatiles::tableName(), 'alumnos.id_portatil = portatiles.id_portatil')->where(['cursos.turno' => 'Tarde', 'estado_matricula' => "Matriculado", 'curso_academico' => Cursan::getCursoActual(), 'portatiles.codigo' => $codigo])->one();
            $listaAlumnosManana = Alumnos::getListaAlumnosManana();
            $listaAlumnosSoloManana = Alumnos::getListaAlumnosSoloManana();
            $listaAlumnosTarde = Alumnos::getListaAlumnosTarde();
            $listaAlumnosSoloTarde = Alumnos::getListaAlumnosSoloTarde();

            return $this->renderAjax('_portatil', [
                'portatil' => $portatil,
                'estado' => $portatil->estado,
                'cargador' => $cargador,
                'almacen' => $almacen,
                'alumnoManana' => $alumnoManana,
                'alumnoTarde' => $alumnoTarde,
                'listaAlumnosManana' => $listaAlumnosManana,
                'listaAlumnosSoloManana' => $listaAlumnosSoloManana,
                'listaAlumnosTarde' => $listaAlumnosTarde,
                'listaAlumnosSoloTarde' => $listaAlumnosSoloTarde,
            ]);

        } else {
            Yii::$app->session->setFlash('error', 'No se encontró ningún portátil con código ' . $codigo);
            return $this->redirect(['index']);
        }

    }

    /**
     * Mostrar la información de un cargador.
     *
     * @param string $codigo Código del cargador
     * @return string
     */
    public function actionCargador($codigo) {

        $this->layout = '/main_nofooter';

        Cargan::sincronizarCargan();
        Cargadores::sincronizarCargadores();

        $cargador = Cargadores::find()->where(['codigo' => $codigo])->one();

        if ($cargador) {

            $portatil = Portatiles::find()->innerJoin(Cargan::tableName(), 'portatiles.id_portatil = cargan.id_portatil')->innerJoin(Cargadores::tableName(), 'cargan.id_cargador = cargadores.id_cargador')->where(['cargadores.id_cargador' => $cargador->id_cargador])->one();
            $almacen = Almacenes::find()->select('almacenes.aula')->distinct()->innerJoin(Cargadores::tableName(), 'almacenes.id_almacen = cargadores.id_almacen')->where(['cargadores.codigo' => $codigo])->scalar();
    
            return $this->renderAjax('_cargador', [
                'cargador' => $cargador,
                'portatil' => $portatil,
                'estado' => $cargador->estado,
                'almacen' => $almacen,
            ]);

        } else {
            Yii::$app->session->setFlash('error', 'No se encontró ningún cargador con código ' . $codigo);
            return $this->redirect(['index']);
        }

    }

    /**
     * Acción para mostrar el panel principal con datos estadísticos.
     *
     * @return string
     */
    public function actionPanel() {

        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        Portatiles::sincronizarPortatiles();
        Cargan::sincronizarCargan();
        Cargadores::sincronizarCargadores();

        $portatilesDisponibles = Portatiles::find()->where('estado = "Disponible"')->count();
        $portatilesNoDisponibles = Portatiles::find()->where('estado = "No disponible"')->count();
        $portatilesAveriados = Portatiles::find()->where('estado = "Averiado"')->count();

        $porcentajePortatilesDisponibles = ($portatilesDisponibles == 0) ? 0 : number_format((float)(($portatilesDisponibles * 100) / ($portatilesDisponibles + $portatilesNoDisponibles + $portatilesAveriados)), 2, '.', '');

        $listadoPortatilesDisponibles = new ActiveDataProvider([
            'query' => Portatiles::find()->where(['estado' => 'Disponible'])->with('almacen'),
            'pagination' => [
                'pageSize' => false,
            ],
        ]);

        $listadoPortatilesAveriados = new ActiveDataProvider([
            'query' => Portatiles::find()->distinct()->where(['estado' => 'Averiado']),
            'pagination' => false,
        ]);

        $cargadoresDisponibles = Cargadores::find()->where('estado = "Disponible"')->count();
        $cargadoresNoDisponibles = Cargadores::find()->where('estado = "No disponible"')->count();
        $cargadoresAveriados = Cargadores::find()->where('estado = "Averiado"')->count();

        $porcentajeCargadoresDisponibles = ($cargadoresDisponibles == 0) ? 0 : number_format((float)(($cargadoresDisponibles * 100) / ($cargadoresDisponibles + $cargadoresNoDisponibles + $cargadoresAveriados)), 2, '.', '');

        $listadoCargadoresDisponibles = new ActiveDataProvider([
            'query' => Cargadores::find()->where(['estado' => 'Disponible'])->with('almacen'),
            'pagination' => [
                'pageSize' => false,
            ],
        ]);

        $listadoCargadoresAveriados = new ActiveDataProvider([
            'query' => Cargadores::find()->distinct()->where(['estado' => 'Averiado']),
            'pagination' => false,
        ]);

        $almacenes = Almacenes::find()->select(['CONCAT("Almacén ", almacenes.aula) AS almacen', 'almacenes.capacidad', 'COALESCE(portatiles.count, 0) + COALESCE(cargadores.count, 0) AS dispositivos'])->leftJoin(['portatiles' => (new \yii\db\Query())->select(['id_almacen', 'COUNT(*) AS count'])->from('Portatiles')->groupBy('id_almacen')], 'almacenes.id_almacen = portatiles.id_almacen')->leftJoin(['cargadores' => (new \yii\db\Query())->select(['id_almacen', 'COUNT(*) AS count'])->from('Cargadores')->groupBy('id_almacen')], 'almacenes.id_almacen = cargadores.id_almacen')->asArray()->all();
        
        $usoCiclo = Alumnos::find()->select(['cursos.sigla', 'COUNT(*) AS cantidad'])->joinWith('cursan')->joinWith('cursan.curso')->where(['cursan.curso_academico' => Cursan::getCursoActual()])->groupBy('cursos.nombre')->asArray()->all();

        return $this->render('panel', [
            'portatilesDisponibles' => $portatilesDisponibles,
            'portatilesNoDisponibles' => $portatilesNoDisponibles,
            'portatilesAveriados' => $portatilesAveriados,
            'porcentajePortatilesDisponibles' => $porcentajePortatilesDisponibles,
            'listadoPortatilesDisponibles' => $listadoPortatilesDisponibles,
            'listadoPortatilesAveriados' => $listadoPortatilesAveriados,
            'cargadoresDisponibles' => $cargadoresDisponibles,
            'cargadoresNoDisponibles' => $cargadoresNoDisponibles,
            'cargadoresAveriados' => $cargadoresAveriados,
            'porcentajeCargadoresDisponibles' => $porcentajeCargadoresDisponibles,
            'listadoCargadoresDisponibles' => $listadoCargadoresDisponibles,
            'listadoCargadoresAveriados' => $listadoCargadoresAveriados,
            'almacenes' => $almacenes,
            'usoCiclo' => $usoCiclo,
        ]);

    }

    /**
     * Acción de login.
     *
     * @return Response|string
     */

views/layouts/main.php
<?php

    /** @var yii\web\View $this */
    /** @var string $content */

    use app\assets\AppAsset;
    use app\widgets\Alert;
    use yii\bootstrap4\Breadcrumbs;
    use yii\bootstrap4\Html;
    use yii\bootstrap4\Nav;
    use yii\bootstrap4\NavBar;

    // Se registra el conjunto de recursos de la aplicación (CSS, JavaScript, etc.).
    AppAsset::register($this);

?>

<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>" class="h-100">
        <head>
            <meta charset="<?= Yii::$app->charset ?>">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <?php $this->registerCsrfMetaTags() ?>
            <title><?= Html::encode($this->title) ?></title>
            <?php $this->head() ?>
            <!-- Favicon -->
            <link rel="shortcut icon" href=<?= Yii::$app->request->baseUrl . "/favicon.ico"; ?> />
            <link rel="icon" type="image/x-icon" href=<?= Yii::$app->request->baseUrl . "/favicon.ico"; ?> />
            <!-- Tipografía -->
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
        </head>
        <body class="d-flex flex-column h-100">
            <?php $this->beginBody() ?>

                <header>
                    <?php

                        // Barra de navegación
                        NavBar::begin([
                            'brandLabel' => Html::img("@web/images/logo_sm.png"), // Logo
                            'brandUrl' => ['/site/index'],
                            'options' => [
                                'class' => 'navbar navbar-expand-md navbar-dark fixed-top', // CSS para encabezado
                            ],
                            'innerContainerOptions' => [
                                'class' => 'container-fluid', // CSS para el contenedor interno del encabezado
                            ],
                        ]);

                            // Elementos del menú
                            $menuItems = [
                                ['label' => 'INICIO', 'url' => ['/site/index']], // Página de inicio
                            ];

                            // Si el usuario no está autenticado, se muestra la opción de iniciar sesión
                            if (Yii::$app->user->isGuest) {
                                $menuItems[] = ['label' => 'INICIAR SESIÓN', 'url' => ['/site/login']];
                            } else {
                                // Si el usuario está autenticado, se muestran opciones adicionales
                                $menuItems[] = ['label' => 'PANEL', 'url' => ['/site/panel']];
                                $menuItems[] = ['label' => 'PORTÁTILES', 'url' => ['/portatiles/index']];
                                $menuItems[] = ['label' => 'APLICACIONES', 'url' => ['/aplicaciones/index']];
                                $menuItems[] = ['label' => 'CARGADORES', 'url' => ['/cargadores/index']];
                                $menuItems[] = ['label' => 'ALMACENES', 'url' => ['/almacenes/index']];
                                $menuItems[] = ['label' => 'ALUMNOS', 'url' => ['/alumnos/index']];
                                $menuItems[] = ['label' => 'CURSOS', 'url' => ['/cursos/index']];
                                // Opción de cerrar sesión, con confirmación mediante POST
                                $menuItems[] = [
                                    'label' => 'CERRAR SESIÓN (' . strtoupper(Yii::$app->user->identity->username) . ')', 
                                    'url' => ['/site/logout'], 
                                    'linkOptions' => ['data-method' => 'post']
                                ];
                            }

                            // Se renderiza el menú de navegación
                            echo Nav::widget([
                                'options' => ['class' => 'navbar-nav ml-auto'],  // Clases CSS para el menú
                                'items' => $menuItems,  // Ítems del menú
                            ]);

                        NavBar::end();

                    ?>
                </header>

                <!-- Contenido de la página -->
                <main role="main" class="flex-shrink-0">
                    <div class="container">
                        <?= Breadcrumbs::widget([
                            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                        ]) ?>
                        <?= Alert::widget() ?>
                        <!-- Contenido de la página -->
                        <?= $content ?>
                    </div>
                </main>

                <!-- Pie de página -->
                <footer class="footer mt-auto py-3 text-muted" style="text-align: center;">
                    <div class="container">
                        <div class="flex-grow-1">
                            <p style="color: #E3E3E3;">Desarrollado por <span style="color: #82C0CC;">Víctor García Murillo</span></p>
                        </div>
                        <div class="flex-shrink-0">
                            <!-- Enlace a GitHub -->
                            <a class="footer-icon" href="https://github.com/Qv1ko/GDCE" target="_blank">
                                <svg class="button-icon" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 512 512">
                                    <title>Proyecto en GitHub</title>
                                    <path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3 .3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5 .3-6.2 2.3zm44.2-1.7c-2.9 .7-4.9 2.6-4.6 4.9 .3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3 .7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3 .3 2.9 2.3 3.9 1.6 1 3.6 .7 4.3-.7 .7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3 .7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3 .7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/>
                                </svg>
                            </a>
                            <!-- Enlace a GitLab -->
                            <a class="footer-icon" href="https://gitlab.com/vgarcia3301646/gdce" target="_blank">
                                <svg class="button-icon" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 512 512">
                                    <title>Proyecto en GitLab</title>
                                    <path d="M503.5 204.6L502.8 202.8L433.1 21C431.7 17.5 429.2 14.4 425.9 12.4C423.5 10.8 420.8 9.9 417.9 9.6C415 9.3 412.2 9.7 409.5 10.7C406.8 11.7 404.4 13.3 402.4 15.5C400.5 17.6 399.1 20.1 398.3 22.9L351.3 166.9H160.8L113.7 22.9C112.9 20.1 111.5 17.6 109.6 15.5C107.6 13.4 105.2 11.7 102.5 10.7C99.9 9.7 97 9.3 94.1 9.6C91.3 9.9 88.5 10.8 86.1 12.4C82.8 14.4 80.3 17.5 78.9 21L9.3 202.8L8.5 204.6C-1.5 230.8-2.7 259.6 5 286.6C12.8 313.5 29.1 337.3 51.5 354.2L51.7 354.4L52.3 354.8L158.3 434.3L210.9 474L242.9 498.2C246.6 500.1 251.2 502.5 255.9 502.5C260.6 502.5 265.2 500.1 268.9 498.2L300.9 474L353.5 434.3L460.2 354.4L460.5 354.1C482.9 337.2 499.2 313.5 506.1 286.6C514.7 259.6 513.5 230.8 503.5 204.6z"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                </footer>

                <style>

                    /* Estilos del contenedor del pie de página */
                    .footer .container {
                        display: flex;
                        justify-content: space-between;
                        align-items: center;
                        flex-wrap: wrap;
                    }

                    /* Ajuste de los elementos del pie de página */
                    .footer .container > div {
                        flex-basis: 48%;
                    }

                    /* Estilos para pantallas pequeñas */
                    @media (max-width: 768px) {
                        .footer .container {
                            justify-content: center;
                            text-align: center;
                        }
                        .footer .container > div {
                            flex-basis: auto;
                            max-width: 100%;
                        }
                    }

                </style>

            <?php $this->endBody() ?>
        </body>
    </html>
<?php $this->endPage() ?>