controllers/CarganController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cargan;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * CarganController implements the CRUD actions for Cargan model.
 */
class CarganController extends Controller {

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lista todos los modelos de Cargan.
     *
     * @return string
     */
    public function actionIndex() {

        // Redirige a la página principal si el usuario no está autenticado
        if(Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $dataProvider = new ActiveDataProvider([
            'query' => Cargan::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);

    }

    /**
     * Crea un nuevo modelo de Cargan.
     * Si la creación es exitosa, redirige a la página index.
     * @return string|\yii\web\Response
     */
    public function actionCreate() {

        $model = new Cargan();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['index']);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);

    }

    /**
     * Actualiza un modelo existente de Cargan.
     * Si la actualización es exitosa, redirige a la página 'index'.
     * @param int $id_carga Id Carga
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException si el modelo no se puede encontrar
     */
    public function actionUpdate($id_carga) {

        $model = $this->findModel($id_carga);

        // Maneja el envío del formulario
        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        // Renderiza la vista 'update' con el modelo
        return $this->render('update', [
            'model' => $model,
        ]);

    }
    
    /**
     * Vincula un cargador a un portátil.
     * @return void
     */
    public function actionVincular() {

        $cargador = Yii::$app->request->post('cargador');
        $portatil = Yii::$app->request->post('portatil');

        if ($cargador !== null && $portatil !== null) {

            // Elimina las relaciones antiguas
            $antiguasCargas = Cargan::find()->where(['id_cargador' => $cargador])->orWhere(['id_portatil' => $portatil])->all();
    
            foreach ($antiguasCargas as $carga) {
                $carga->delete();
            }
    
            // Crea una nueva relación
            $model = new Cargan();
            $model->id_cargador = $cargador;
            $model->id_portatil = $portatil;
            $model->save();

            Yii::$app->session->setFlash('success', 'El cargador se ha vinculado correctamente.');

        } elseif ($cargador !== null && $portatil === null) {

            // Elimina las relaciones antiguas del cargador
            $antiguasCargas = Cargan::find()->where(['id_cargador' => $cargador])->all();
    
            foreach ($antiguasCargas as $carga) {
                $carga->delete();
            }

        }

    }

    /**
     * Elimina un modelo existente de Cargan.
     * Si la eliminación es exitosa, redirige a la página index.
     * @param int $id_carga Id Carga
     * @return \yii\web\Response
     * @throws NotFoundHttpException si el modelo no se puede encontrar
     */
    public function actionDelete($id_carga) {
        $this->findModel($id_carga)->delete();
        return $this->redirect(['index']);
    }

    /**
     * Encuentra el modelo Cargan basado en su clave primaria.
     * Si el modelo no se encuentra, se lanza una excepción HTTP 404.
     * @param int $id_carga Id Carga
     * @return Cargan el modelo cargado
     * @throws NotFoundHttpException si el modelo no se puede encontrar
     */
    protected function findModel($id_carga) {
        if (($model = Cargan::findOne(['id_carga' => $id_carga])) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('No existe la relación entre el cargador y el portátil');
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Almacenes;
use app\models\Alumnos;
use app\models\Cargadores;
use app\models\Cargan;
use app\models\Cursan;
use app\models\Cursos;
use app\models\LoginForm;
use app\models\Portatiles;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Mostrar la página de inicio.
     *
     * @return string
     */
    public function actionIndex() {
        return $this->render('index');
    }

    /**
     * Mostrar la información de un portátil.
     *
     * @param string $codigo Código del portátil
     * @return string
     */
    public function actionPortatil($codigo) {

        $this->layout = '/main_nofooter';

        Cargan::sincronizarCargan();
        $portatil = Portatiles::find()->where(['codigo' => $codigo])->one();

        if ($portatil) {

            $portatil->sincronizarPortatil($portatil);

            $cargador = Cargadores::find()->select('cargadores.codigo')->distinct()->innerJoin(Cargan::tableName(), 'cargadores.id_cargador = cargan.id_cargador')->innerJoin(Portatiles::tableName(), 'cargan.id_portatil = portatiles.id_portatil')->where(['portatiles.codigo' => $codigo])->scalar();
            $almacen = Almacenes::find()->select('almacenes.aula')->distinct()->innerJoin(Portatiles::tableName(), 'almacenes.id_almacen = portatiles.id_almacen')->where(['portatiles.codigo' => $codigo])->scalar();
            $alumnoManana = Alumnos::find()->innerJoin(Cursan::tableName(), 'alumnos.id_alumno = cursan.id_alumno')->innerJoin(Cursos::tableName(), 'cursan.id_curso = cursos.id_curso')->innerJoin(Portatiles::tableName(), 'alumnos.id_portatil = portatiles.id_portatil')->where(['cursos.turno' => 'Mañana', 'estado_matricula' => "Matriculado", 'curso_academico' => Cursan::getCursoActual(), 'portatiles.codigo' => $codigo])->one();
            $alumnoTarde = Alumnos::find()->innerJoin(Cursan::tableName(), 'alumnos.id_alumno = cursan.id_alumno')->innerJoin(Cursos::tableName(), 'cursan.id_curso = cursos.id_curso')->innerJoin(Portatiles::tableName(), 'alumnos.id_portatil = portatiles.id_portatil')->where(['cursos.turno' => 'Tarde', 'estado_matricula' => "Matriculado", 'curso_academico' => Cursan::getCursoActual(), 'portatiles.codigo' => $codigo])->one();
            $listaAlumnosManana = Alumnos::getListaAlumnosManana();
            $listaAlumnosSoloManana = Alumnos::getListaAlumnosSoloManana();
            $listaAlumnosTarde = Alumnos::getListaAlumnosTarde();
            $listaAlumnosSoloTarde = Alumnos::getListaAlumnosSoloTarde();

            return $this->renderAjax('_portatil', [
                'portatil' => $portatil,
                'estado' => $portatil->estado,
                'cargador' => $cargador,
                'almacen' => $almacen,
                'alumnoManana' => $alumnoManana,
                'alumnoTarde' => $alumnoTarde,
                'listaAlumnosManana' => $listaAlumnosManana,
                'listaAlumnosSoloManana' => $listaAlumnosSoloManana,
                'listaAlumnosTarde' => $listaAlumnosTarde,
                'listaAlumnosSoloTarde' => $listaAlumnosSoloTarde,
            ]);

        } else {
            Yii::$app->session->setFlash('error', 'No se encontró ningún portátil con código ' . $codigo);
            return $this->redirect(['index']);
        }

    }

    /**
     * Mostrar la información de un cargador.
     *
     * @param string $codigo Código del cargador
     * @return string
     */
    public function actionCargador($codigo) {

        $this->layout = '/main_nofooter';

        Cargan::sincronizarCargan();
        Cargadores::sincronizarCargadores();

        $cargador = Cargadores::find()->where(['codigo' => $codigo])->one();

        if ($cargador) {

            $portatil = Portatiles::find()->innerJoin(Cargan::tableName(), 'portatiles.id_portatil = cargan.id_portatil')->innerJoin(Cargadores::tableName(), 'cargan.id_cargador = cargadores.id_cargador')->where(['cargadores.id_cargador' => $cargador->id_cargador])->one();
            $almacen = Almacenes::find()->select('almacenes.aula')->distinct()->innerJoin(Cargadores::tableName(), 'almacenes.id_almacen = cargadores.id_almacen')->where(['cargadores.codigo' => $codigo])->scalar();
    
            return $this->renderAjax('_cargador', [
                'cargador' => $cargador,
                'portatil' => $portatil,
                'estado' => $cargador->estado,
                'almacen' => $almacen,
            ]);

        } else {
            Yii::$app->session->setFlash('error', 'No se encontró ningún cargador con código ' . $codigo);
            return $this->redirect(['index']);
        }

    }

    /**
     * Acción para mostrar el panel principal con datos estadísticos.
     *
     * @return string
     */
    public function actionPanel() {

        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        Portatiles::sincronizarPortatiles();
        Cargan::sincronizarCargan();
        Cargadores::sincronizarCargadores();

        $portatilesDisponibles = Portatiles::find()->where('estado = "Disponible"')->count();
        $portatilesNoDisponibles = Portatiles::find()->where('estado = "No disponible"')->count();
        $portatilesAveriados = Portatiles::find()->where('estado = "Averiado"')->count();

        $porcentajePortatilesDisponibles = ($portatilesDisponibles == 0) ? 0 : number_format((float)(($portatilesDisponibles * 100) / ($portatilesDisponibles + $portatilesNoDisponibles + $portatilesAveriados)), 2, '.', '');

        $listadoPortatilesDisponibles = new ActiveDataProvider([
            'query' => Portatiles::find()->where(['estado' => 'Disponible'])->with('almacen'),
            'pagination' => [
                'pageSize' => false,
            ],
        ]);

        $listadoPortatilesAveriados = new ActiveDataProvider([
            'query' => Portatiles::find()->distinct()->where(['estado' => 'Averiado']),
            'pagination' => false,
        ]);

        $cargadoresDisponibles = Cargadores::find()->where('estado = "Disponible"')->count();
        $cargadoresNoDisponibles = Cargadores::find()->where('estado = "No disponible"')->count();
        $cargadoresAveriados = Cargadores::find()->where('estado = "Averiado"')->count();

        $porcentajeCargadoresDisponibles = ($cargadoresDisponibles == 0) ? 0 : number_format((float)(($cargadoresDisponibles * 100) / ($cargadoresDisponibles + $cargadoresNoDisponibles + $cargadoresAveriados)), 2, '.', '');

        $listadoCargadoresDisponibles = new ActiveDataProvider([
            'query' => Cargadores::find()->where(['estado' => 'Disponible'])->with('almacen'),
            'pagination' => [
                'pageSize' => false,
            ],
        ]);

        $listadoCargadoresAveriados = new ActiveDataProvider([
            'query' => Cargadores::find()->distinct()->where(['estado' => 'Averiado']),
            'pagination' => false,
        ]);

        $almacenes = Almacenes::find()->select(['CONCAT("Almacén ", almacenes.aula) AS almacen', 'almacenes.capacidad', 'COALESCE(portatiles.count, 0) + COALESCE(cargadores.count, 0) AS dispositivos'])->leftJoin(['portatiles' => (new \yii\db\Query())->select(['id_almacen', 'COUNT(*) AS count'])->from('Portatiles')->groupBy('id_almacen')], 'almacenes.id_almacen = portatiles.id_almacen')->leftJoin(['cargadores' => (new \yii\db\Query())->select(['id_almacen', 'COUNT(*) AS count'])->from('Cargadores')->groupBy('id_almacen')], 'almacenes.id_almacen = cargadores.id_almacen')->asArray()->all();
        
        $usoCiclo = Alumnos::find()->select(['cursos.sigla', 'COUNT(*) AS cantidad'])->joinWith('cursan')->joinWith('cursan.curso')->where(['cursan.curso_academico' => Cursan::getCursoActual()])->groupBy('cursos.nombre')->asArray()->all();

        return $this->render('panel', [
            'portatilesDisponibles' => $portatilesDisponibles,
            'portatilesNoDisponibles' => $portatilesNoDisponibles,
            'portatilesAveriados' => $portatilesAveriados,
            'porcentajePortatilesDisponibles' => $porcentajePortatilesDisponibles,
            'listadoPortatilesDisponibles' => $listadoPortatilesDisponibles,
            'listadoPortatilesAveriados' => $listadoPortatilesAveriados,
            'cargadoresDisponibles' => $cargadoresDisponibles,
            'cargadoresNoDisponibles' => $cargadoresNoDisponibles,
            'cargadoresAveriados' => $cargadoresAveriados,
            'porcentajeCargadoresDisponibles' => $porcentajeCargadoresDisponibles,
            'listadoCargadoresDisponibles' => $listadoCargadoresDisponibles,
            'listadoCargadoresAveriados' => $listadoCargadoresAveriados,
            'almacenes' => $almacenes,
            'usoCiclo' => $usoCiclo,
        ]);

    }

    /**
     * Acción de login.
     *
     * @return Response|string
     */

views/site/error.php
<?php

    /** @var yii\web\View $this */
    /** @var string $name */
    /** @var string $message */
    /** @var Exception$exception */

    use yii\helpers\Html;

    // Título de la página
    $this->title = $name;
    
?>

<div class="site-error container">
    <div class="row justify-content-center">
        <div class="col-md-6">

            <!-- Título de la página -->
            <h1 class="text-center mb-4"><?= Html::encode($this->title) ?></h1>

            <!-- Mensaje de error -->
            <div class="alert alert-danger mb-4">
                <?= nl2br(Html::encode($message)) ?>
            </div>

            <p class="mb-4 text-center">
                Se produjo un error al procesar su solicitud
            </p>

            <!-- Enlace de contacto -->
            <p class="mb-4 text-center">
                <?= Html::a('Contáctanos', 'https://github.com/Qv1ko/GDCE/issues', ['target' => '_blank']) ?> si el error persiste
            </p>

            <!-- Enlace para volver al inicio -->
            <p class="text-center">
                <?= Html::a('Volver al inicio', ['site/index'], ['class' => 'btn btn-primary']) ?>
            </p>

        </div>
    </div>
</div>

views/site/index.php
<?php

    /**
     * @var yii\web\View $this
     */

    use yii\bootstrap4\Modal;
    use yii\helpers\Url;

    // Título de la página
    $this->title = 'Inicio';

    // Registrar archivos JavaScript
    $this->registerJsFile('@web/js/lectorQr.js', ['position' => \yii\web\View::POS_HEAD]);
    $this->registerJsFile('@web/js/jquery.js', ['position' => \yii\web\View::POS_HEAD]);

?>

<div class="site-index">
    <div class="container">

        <!-- Crear una fila con contenido centrado -->
        <div class="row d-flex justify-content-center">
            <div class="col-12">
                <h1>Escanear código QR</h1>
            </div>
            <div class="col-md-12 col-10 d-flex justify-content-center">
                <!-- Crear una columna para el lector de códigos QR -->
                <div id="reader" style="margin: 8px 0;"></div>
            </div>
        </div>

        <hr>

        <div class="row d-flex justify-content-center">
            <!-- Crear una columna centrada para el encabezado h3 -->
            <div class="col-12">
                <h2>Ingresar código del portátil</h2>
            </div>
            <!-- Crear una columna para el grupo de entrada -->
            <div class="col-7 col-xl-2 col-lg-3 col-md-3 col-sm-4" style="margin: 8px 0;">
                <!-- Crear un grupo de entrada -->
                <div class="input-group">
                    <input type="text" id="searchInput" class="form-control" placeholder="ej. 123A">
                    <div class="input-group-append">
                        <!-- Crear un botón para escanear el código QR o ingresar el código de portátil -->
                        <button class="btn btn-primary" id="buscarPortatil">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-search">
                                <title>Buscar portátil</title>
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"/>
                                <path d="M21 21l-6 -6"/>
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<?php

    // Modal para mostrar información del portátil
    Modal::begin([
        'title' => '<h2 class="col-12" id="tituloPortatil"></h2>',
        'id' => 'modalPortatil',
        'size' => 'modal-lg',
        'closeButton' => false
    ]);
        echo "<div id='contenidoPortatil'></div>";
    Modal::end();

    // Modal para mostrar información del cargador
    Modal::begin([
        'title' => '<h2 class="col-12" id="tituloCargador"></h2>',
        'id' => 'modalCargador',
        'closeButton' => false
    ]);
        echo "<div id='contenidoCargador'></div>";
    Modal::end();

?>

<!-- Script de JavaScript para controlar el escaner y el buscador de códigos -->
<script>

    const scanner = new Html5QrcodeScanner('reader', {
        qrbox: {
            width: 240,
            height: 240,
        },
        fps: 20,
    });

    // Renderizar el escáner de códigos QR
    scanner.render(success, error);

    // Función para manejar un escaneo de código QR exitoso
    function success(result) {
        buscar(result);
        scanner.clear();
        document.getElementById('reader').remove();
    }

    // Función para manejar errores del escáner de códigos QR
    function error(err) {
        console.error(err);
    }

    // Manejar el evento de clic en el botón de búsqueda
    $('#buscarPortatil').click(function() {
        var busqueda = $('#searchInput').val();
        buscar(busqueda);
    });

    // Función para buscar el dispositivo basado en el código
    function buscar(resultado) {

        var recortarResultado = false;
        var patronPortatil, patronCargador;

        if (resultado.length !== 4) {
            patronPortatil = /^P\d{3}[A-Z]$/;
            patronCargador = /^C\d{3}[A-Z]$/;
            recortarResultado = true;
        } else {
            patronPortatil = /^\d{3}[a-zA-Z]$/;
            patronCargador = /^\d{3}[a-zA-Z]$/;
        }

        if (patronPortatil.test(resultado)) {
            mostrarModal('Portátil', resultado, recortarResultado, '#tituloPortatil', '#contenidoPortatil', '<?= Url::to(["site/portatil"]) ?>', '#modalPortatil');
        } else if (patronCargador.test(resultado)) {
            mostrarModal('Cargador', resultado, recortarResultado, '#tituloCargador', '#contenidoCargador', '<?= Url::to(["site/cargador"]) ?>', '#modalCargador');
        } else {
            alert('El código del dispositivo debe tener el formato correcto (ej. 123A)');
            location.reload();
        }

    }

    // Función para mostrar el modal
    function mostrarModal(tipo, resultado, recortar, tituloSelector, contenidoSelector, url, modalSelector) {

        var codigo = (recortar) ? resultado.substring(1) : resultado;
        document.querySelector(tituloSelector).innerText = tipo + ' ' + codigo.toUpperCase();

        $.get(url, {codigo: codigo}, function(data) {
            $(contenidoSelector).html(data);
            $(modalSelector).modal('show');
        });

        $(modalSelector).on('hidden.bs.modal', function () {
            location.reload();
        });

    }

</script>

views/site/login.php
<?php

    /** @var yii\web\View $this */
    /** @var yii\bootstrap4\ActiveForm $form */
    /** @var app\models\LoginForm $model */

    use yii\bootstrap4\ActiveForm;
    use yii\bootstrap4\Html;

    // Título de la página
    $this->title = 'Iniciar sesión';

?>

<style>
    .site-login {
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }
    .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 10px;
        font-size: 16px;
    }
    .form-group {
        margin-bottom: 15px;
    }
    .btn {
        font-size: 16px;
        width: 100%;
        padding: 14px 20px;
    }
</style>

<div class="site-login">
    <div class="container">

        <!-- Título de la página -->
        <h1><?= Html::encode($this->title) ?></h1>

        <?php $form = ActiveForm::begin([
            'id' => 'login-form',
            'layout' => 'horizontal',
            'fieldConfig' => [
                'template' => "{label}\n{input}\n{error}",
                'labelOptions' => ['class' => 'col-form-label mr-lg-7'],
                'inputOptions' => ['class' => 'form-control'],
                'errorOptions' => ['class' => 'invalid-feedback'],
            ],
        ]); ?>

            <!-- Campo para el nombre de usuario -->
            <?= $form->field($model, 'username', [
                'inputOptions' => [
                    'placeholder' => 'Escribe el nombre del usuario',
                    'class' => 'form-control',
                ],
            ])->label($model->getAttributeLabel('username'))->textInput(['autofocus' => true]) ?>

            <!-- Campo para la contraseña -->
            <?= $form->field($model, 'password', [
                'inputOptions' => [
                    'placeholder' => 'Escribe la contraseña del usuario',
                    'class' => 'form-control',
                ],
            ])->label($model->getAttributeLabel('password'))->passwordInput() ?>

            <!-- Campo para "Recordarme" -->
            <?= $form->field($model, 'rememberMe')->checkbox([
                'template' => "<div class=\"custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
            ]) ?>

            <!-- Botón de enviar -->
            <div class="form-group">
                <?= Html::submitButton('INICIAR SESIÓN', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>